const express=require('express')
const router=express.Router();
const controller=require("../../controllers/client/user.controller")
const validate=require("../../validates/client/user.validate.js")
const authMiddleware=require("../../middlewares/client/auth.middleware.js")
router.get('/register',controller.register)
router.post('/register',validate.register,controller.registerPost)
router.get('/login',controller.login)
router.post('/login',validate.login,controller.loginPost)
router.get('/logout',controller.logout)
router.get('/password/forgot',controller.forgotpassword)
router.post('/password/forgot',validate.forgotpassword,controller.forgotpasswordPost)
router.get('/password/otp',controller.otpPassword)
router.post('/password/otp',controller.otpPasswordPost)
router.get('/password/reset',controller.resetPassword)
router.post('/password/reset',validate.resetPassword,controller.resetPasswordPost)
router.get('/info',authMiddleware.reqAuth,controller.infoUser)
module.exports=router;